### ISSUE TITLE
GitHub Pages link not working 

### ISSUE THREAD

**Issue by mstackhouse** [eddelbuettel/rcppsimdjson#87]
The link https://eddelbuettel.github.io/rcppsimdjson/ is returning a 404.

**Comment by eddelbuettel** [comment]
Ok, thanks for noticing.  That is also normal and expected.  Where did you see a link to that URL?  Or in other words what made you think that should be something?

I only use docs/ to serve two pngs.

**Comment by mstackhouse** [comment]
Hi @eddelbuettel,

I was looking for a package website associated with RCppSimdJson and it looks like there's a GitHub pages build setup for the website: https://github.com/eddelbuettel/rcppsimdjson/actions/runs/4975273475. The link from the pages build there is what I've copied.

**Comment by eddelbuettel** [comment]
Thanks for the follow-up @mstackhouse 

In essence, that is a problem you have with GitHub. As I said yesterday, I take advantage of `docs/` to serve (all but two) files via GH Pages (so that the README can reference it also at eg CRAN).  

That leads GH to autorun some conversion jobs I cannot turn off (I tried with `.nojekyll` and what not).  But at the end of the day your inference that there must a site because the conversions runs is not correct.  That's all.
